# -*- coding: utf-8 -*-
"""DeepLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KL37KIoVSpnU3fD9pd4VyTp3Vyricboe
"""

import tensorflow as tf

tensor_zero_d = tf.constant(4)

print(tensor_zero_d)

tensor_bool = tf.constant([True,False,True])

print(tensor_bool)

tensor_string = tf.constant(['Hello World','Hi'])

print(tensor_string)

tensor_one_d = tf.constant([1,23,4.9,5])

print(tensor_one_d)

tensor_two_d = tf.constant([
    [2,3,4],
    [3,4,5],
    [6,7,5],
    [8,2,1]
    ])

tensor_two_d

tensor_three_d = tf.constant([
    [[3,5,14],
 [4,2,1]],
[[2,4,5],
 [6,7,-1]],
[[3,4,5],
 [5,4,2]],
[[4,7,8],
 [3,3,2]]
])

print(tensor_three_d)

print(tensor_three_d.ndim)

tensor_one_d_casting = tf.constant([2,3,-1,4],dtype=tf.float32)

print(tensor_one_d_casting)

import numpy as np

np_array = np.array([3,4,5,6])

print(np_array)

tensor_converted = tf.convert_to_tensor(np_array)

print(tensor_converted)

eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=4,
    batch_shape=(3,),
    dtype=tf.dtypes.float64,
    name=None
)

print(3*eye_tensor)

fill_tensor = tf.fill(
    [2,3], 5, name=None, layout=None
)
print(fill_tensor)

ones_tensor = tf.ones(
    [5,4,5],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(ones_tensor)

"""# Indexing In Tensor"""

tensor_index = tf.constant([
    [[1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [3,4,5,2,1]],
    [[3,4,5,6,7],
    [4,5,6,7,8],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [3,3,2,3,4]]
     ])

print(tensor_index[0:2,0:3,1:4])
print(tensor_index[...,2])

"""# TensorFlow Math Function Uses"""

absal_tensor = tf.math.abs(
    x=54.4, name=None
)

print(absal_tensor)

sqrt_tf = tf.math.sqrt(tf.math.abs(-9.0))
print(sqrt_tf)

tf_abs = tf.math.abs([[-2,3,-4],
                      [-2,-6,-7],
                      ])

print(tf_abs)

x_argmax = tf.constant([1,6,3,4])

print(tf.math.argmax(x_argmax))

print(tf.math.argmin(tensor_index,0))

top_value = tf.math.top_k([2,3,4,5],2)

print(top_value)

tensor_index = tf.constant([
    [1,2,4,5,6],
    [5,32,45,87,12]])
top_value_2_d = tf.math.top_k(tensor_index,2)

print(top_value_2_d)

x1 = tf.constant([[1,2,3,4],
                 [4,5,6,7]])
x2 = tf.constant([[5,6,1],
                 [1,1,1],
                 [3,2,1],
                 [1,1,1]])
print(x1.shape,x2.shape)

matrix_mul = tf.linalg.matmul(x1,x2,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type=None,grad_a=False,grad_b=False,name=None)

matrix_mul

import numpy as np

a = tf.constant(np.random.randint(5,30,36,dtype=np.int32),shape=[3,3,4])

print(a)

print(x1@x2)

tf.transpose(x1)

tf.transpose(x2)

b = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]],dtype=np.float32)

svu = tf.linalg.svd(b)

#print(s)
#print(u)
print(v)

tf.linalg.eigvalsh(
    b, name=None
)

c = tf.constant([[1,2],
                 [3,4]],dtype=np.float64)

tf.linalg.eigvalsh(
    c, name=None
)

A = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]],dtype=np.float32)

B = tf.constant([[1,1,4],
                 [2,5,5],
                 [1,3,2]],dtype=np.float32)

print('MatMul\n',tf.matmul(A,B))
print('Einsum\n',tf.einsum('ij,jk->ik',A,B))

tf.linalg.eigvals(
    A, name=None
)

print(A*B)

a1 = tf.constant(np.random.randint(-3,6,24,dtype=np.int64),shape=[2,3,4])

a2 = tf.constant(np.random.randint(-3,8,40,dtype=np.int64),shape=[2,4,5])

a1

a2

print(tf.matmul(a1,a2))



import torch

# Define two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Element-wise multiplication
result = tensor1 * tensor2

print(result)

print('MatMul\n',np.sum(tf.constant(a1)))

a3 = tf.constant([[[1,2,3,4,5,6,7,8]]])
print(tf.expand_dims(a3,axis=0))

reshaped = tf.reshape(a3,[2,4])

for i in range(2):
  a3 = tf.squeeze(a3,axis=0)
print(a3)

print(reshaped)

reshaped1 = tf.reshape(a3,[2,2,2])

print(reshaped1)

reshaped3 = tf.reshape(a3,[1,1,8,1])

print(reshaped3)

print(tf.expand_dims(a2,axis=1))

tf.concat([a1,a2],axis=0)

t1 = tf.constant([[1,2,3,4],
                  [3,2,1,4],
                  [3,3,4,5]])
t2 = tf.constant([[1,2,8,4],
                  [3,2,4,4],
                  [3,3,2,5]])

tf.concat([t1,t2],axis=1)

tf.concat([t1,t2],axis=0)

tf.stack([t1,t2,t1])

params = tf.constant(['p0','p1','p2','p3','p4'])

params[1:3+2]

tf.gather(params,[0,4,3])

params1 = tf.constant([[0,1.0,2.0],
                       [10.0,11.0,12.0],
                       [19.0,18.0,13.0]])

tf.gather(params1,[0,2],axis=1)

indices = [[1,1],
           [3,1]]
params = [[10,20],
          [30,40],
          [50,60],
          [70,80]]
tf.gather_nd(params,indices)

T, F = (True, False)

print(tf.ragged.boolean_mask(data = tf.ragged.constant[[1,2,3],[4,5,6],[4],[2,2,2]], mask = tf.ragged.constant[[T,F,F],[F,F,F],[F],[T,F,T]]))

